on:
  push:
    branches:
      - master







     jobs:
       build:
         runs on: ubuntu-latest


         steps:
           - uses: actions/checkout@v3

           - name: "login to docker"
             run: docker login --username ${{ srcrets.DOCKER_USERNAME }} --password &{{ secrets.DOCKER_TOCKEN }}
           - name: "build docker img"
             run: docker build -t ${{ srcrets.DOCKER_USERNAME }}/myimage

           - name: "push to docker"
             run: docker push ${{ srcrets.DOCKER_USERNAME }}







